---
title: "MA415 Assignment 1"
author: "Kevin Chan"
date: "January 23 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## 1.
###(a)
```{r}
      1:20
```
###(b)
````{r}
      20:1
```
###(c)
````{r}
      c(1:20, 19:1)
```
###(d)
```{r}
      tmp <- c(4,6,3)
```
###(e)
```{r}
      rep(tmp, 10)
```
###(f) 
```{r}
      rep(tmp, 11, length = 31)
```
###(g) 
```{r}
      rep(tmp, c(10, 20, 30))
```
## 2. 
```{r}
      x <- seq(3,6,by=0.1)
      exp(x)*cos(x)
```
## 3. 
###(a)
```{r}
      i <- seq(3,36,by=3)
      j<- seq(1,34,by=3)
      ThreeA <- (0.1^i*0.2^j)
      ThreeA
```
###(b)
```{r}
      ThreeB <- (2^(1:25)/(1:25))
      ThreeB
```
## 4. 
###(a)
```{r}
      sum((10:100)^3+4*(10:100)^2)
```
###(b)
```{r}
      sum((2^(1:25)/(1:25))+(3^(1:25)/(1:25)^2))
```
## 5. 
###(a)
```{r}
      n <- paste(1:30)
      label <- paste("label ", n)
      label
```
###(b)
```{r}
      fn <- paste0("fn",n)
      fn
```
## 6. 
###(a)
```{r}
      set.seed(50)
      xVec <- sample(0:999, 250, replace=T)
      yVec <- sample(0:999, 250, replace=T)
      yminusx <- yVec[-1] - xVec[-length(xVec)]
      yminusx
```
###(b) Create the vector (sin(y1)/cos(x2),sin(y2)/cos(x3), . . . ,sin(yn−1)/cos(xn)).
```{r}
      sinycosx <- sin(yVec[-length(yVec)])/cos(xVec[-1])
      sinycosx
```
###(c) 
```{r}
      xVecLength <- length(xVec)
      xAdd <- xVec[-c(xVecLength - 1, xVecLength)] + 2*xVec[-c(1, xVecLength)] -       xVec[-c(1,2)]
      xAdd
```
###(d)
```{r}
      xsum <- sum(exp(-xVec[-1])/(xVec[-length(xVec)]+10))
      xsum
```
## 7. This question uses the vectors xVec and yVec created in the previous question and the functions sort, order, mean, sqrt, sum and abs.
###(a) 
```{r}
      yVec[yVec>600]
```
###(b) 
```{r}
      (1:length(yVec))[yVec>600]
```
###(c) 
```{r}
      xVec[yVec>600]
```
###(d) 
```{r}
      sqrt(abs(xVec-mean(xVec)))
```
###(e) 
```{r}
      sum(yVec>max(yVec)-200)
```
###(f) 
```{r}
      sum(xVec%%2==0)
```
###(g) 
```{r}
      xVec[order(yVec)]
```
###(h) 
```{r}
      yVec[c(T,F,F)]
```
## 8. 
```{r}
      1 + sum(cumprod(seq(2,38,by=2)/seq(3,39,by=2)))
```
